# Generated by Django 5.0.6 on 2024-05-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promelec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promelecproduct',
            name='category',
        ),
    ]
