# Generated by Django 5.0.6 on 2024-05-11 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promelec', '0002_remove_promelecproduct_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='promelecproduct',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='promelec.promeleccategory', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
