# Generated by Django 5.0.6 on 2024-05-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promelec', '0007_alter_promelecorder_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promelecorder',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='promelecinventory',
            name='load_state',
            field=models.IntegerField(choices=[(0, 'Ожидание'), (1, 'Загружено')], default=0, verbose_name='Статус загрузки'),
        ),
    ]
