# Generated by Django 5.0.6 on 2024-05-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promelec', '0008_alter_promelecorder_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promelecinventory',
            name='load_state',
        ),
    ]
