# Generated by Django 5.0.6 on 2024-05-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promelec', '0009_remove_promelecinventory_load_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitemapURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('url', models.URLField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'URL карты сайта',
                'verbose_name_plural': 'URL карты сайта',
            },
        ),
    ]
